data_path: './data/train_small.csv'
predicted_data_path: '/data/pred.csv'

spark:
  master: local
  app_name: MovieLens

models:
  num_features: 10000
  tf_path: './models/TF'
  idf_path: './models/IDF'
  normalizer_path: './models/norm'
  brp_path: './models/BRP'

random_seed: 42
n_samples_to_predict: 10
