version: '3.8'
services:
   web:
       build: .
       command: bash -c "/opt/spark/bin/spark-submit src/train.py && /opt/spark/bin/spark-submit src/predict.py"
       ports:
           - 8000:8000
       image: asoldatenkov/spark-movielens